# Generated by Django 5.2 on 2025-04-19 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[('Alimentación', 'Alimentación'), ('Transporte', 'Transporte'), ('Educación', 'Educación'), ('Ocio', 'Ocio'), ('Salud', 'Salud')], max_length=50, verbose_name='Nombre')),
                ('personalizada', models.CharField(blank=True, max_length=50, verbose_name='Personalizada')),
                ('es_predefinida', models.BooleanField(default=False, verbose_name='Predefinida')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('periodo', models.CharField(default='mensual', max_length=20, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Recurrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=10, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('frecuencia', models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual')], max_length=10, verbose_name='Frecuencia')),
                ('proxima_fecha', models.DateField(verbose_name='Próxima fecha')),
            ],
            options={
                'verbose_name': 'Recurrencia',
                'verbose_name_plural': 'Recurrencias',
            },
        ),
    ]
